name: 'mirror'
on:
  push:
    branches:
      - main
  schedule:
    - cron:  "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout depot tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH

      - name: Build R8 Jar
        run: ./tools/gradle.py d8 r8
